"""empty message

Revision ID: 5aea50727992
Revises: 0e648fcb8ef6
Create Date: 2016-06-20 11:16:36.869000

"""

# revision identifiers, used by Alembic.
revision = '5aea50727992'
down_revision = '0e648fcb8ef6'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_date')
    ### end Alembic commands ###
