"""empty message

Revision ID: a5ee63d173dd
Revises: 01a1fa5b87f5
Create Date: 2018-01-08 00:07:31.867362

"""

# revision identifiers, used by Alembic.
revision = 'a5ee63d173dd'
down_revision = '01a1fa5b87f5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('expertise', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('occupation_detail', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('recruitment', sa.String(), nullable=True))
    op.add_column('ticket_holders', sa.Column('welcome_reception', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'welcome_reception')
    op.drop_column('ticket_holders', 'recruitment')
    op.drop_column('ticket_holders', 'occupation_detail')
    op.drop_column('ticket_holders', 'occupation')
    op.drop_column('ticket_holders', 'gender')
    op.drop_column('ticket_holders', 'expertise')
    # ### end Alembic commands ###
