"""empty message

Revision ID: e9d61dbd0cb8
Revises: a5ee63d173dd
Create Date: 2018-02-10 14:28:46.614028

"""

# revision identifiers, used by Alembic.
revision = 'e9d61dbd0cb8'
down_revision = 'a5ee63d173dd'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_holders', sa.Column('unesco_hackathon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_holders', 'unesco_hackathon')
    # ### end Alembic commands ###
